# Generated by Django 5.0 on 2024-04-23 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="Membership Number"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                ("email", models.EmailField(max_length=200, verbose_name="E-Mail")),
            ],
        ),
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start", models.DateField(verbose_name="start")),
                ("end", models.DateField(blank=True, null=True, verbose_name="end")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The amount to be paid in the chosen interval",
                        max_digits=8,
                        verbose_name="Membership Fee",
                    ),
                ),
                (
                    "interval",
                    models.IntegerField(
                        choices=[
                            (1, "Monthly"),
                            (3, "Quarterly"),
                            (6, "Biannually"),
                            (12, "Annually"),
                        ],
                        help_text="How often does the member pay their fees?",
                        verbose_name="Payment Interval",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="members.member",
                    ),
                ),
            ],
        ),
    ]
