# Generated by Django 5.0 on 2024-06-18 13:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="has_key",
            field=models.BooleanField(default=False, verbose_name="Has physical key?"),
        ),
        migrations.AddField(
            model_name="member",
            name="phone_number",
            field=models.CharField(
                blank=True, max_length=16, verbose_name="Phone number"
            ),
        ),
    ]
