# Generated by Django 5.0 on 2024-06-25 12:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0003_remove_member_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membership",
            name="end",
            field=models.DateField(
                blank=True, null=True, verbose_name="End Membership"
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="start",
            field=models.DateField(verbose_name="Start Membership"),
        ),
    ]
