# Generated by Django 5.0 on 2024-05-01 19:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookkeeping", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cashbook",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
