# Generated by Django 5.0 on 2024-02-27 01:40

from django.db import migrations, models
from django.utils.text import slugify


def set_cash_book_slugs(apps, schema_editor):
    CashBook = apps.get_model("bookkeeping", "CashBook")
    cash_books = CashBook.objects.all()
    for cash_book in cash_books:
        cash_book.slug = slugify(cash_book.name)
        cash_book.save()


class Migration(migrations.Migration):
    dependencies = [
        ("bookkeeping", "0005_rename_account_cashbook_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cashbook",
            name="slug",
            field=models.SlugField(default="", max_length=64),
        ),
        migrations.RunPython(set_cash_book_slugs, atomic=True),
        migrations.AlterField(
            model_name="cashbook",
            name="slug",
            field=models.SlugField(max_length=64, unique=True),
        ),
    ]
