# Generated by Django 5.0 on 2024-02-18 14:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookkeeping", "0003_add_a_general_unique_transaction_identifier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.SmallIntegerField(
                choices=[(1, "Deposit"), (2, "Expense"), (3, "Income"), (4, "Withdraw")]
            ),
        ),
    ]
